ModECI/MDF

MDF.py, Simple.json, Simple.py, SimpleScheduler.py, utils.py
Can be used for a simple execution/evaluation of the values nodes, passing values along edges as required
=> A Simple Scheduler: builds an evaluable version of the connected graph

README.md
- describe condition entry
- include as direct entry to graph
=> README: update spec for conditions

examples/ABCD.json, examples/ABCD.nmllite.json, examples/ABCD.py, examples/ABCD.yaml, examples/Simple.json, examples/Simple.nmllite.json, examples/Simple.py, examples/Simple.yaml, modeci_mdf/SimpleScheduler.py, modeci_mdf/export/GraphViz.py, modeci_mdf/export/NeuroML.py, modeci_mdf/utils.py, setup.py
For https://github.com/ModECI/MDF/issues/14.
Requires a branch of NeuroMLlite (which will be merged after more testing). See https://github.com/ModECI/MDF/blob/3cd67c61cb0e6837488fab1408db38b91a7bb958/.travis.yml#L14-L19 for details
=> Simplified format

src/modeci_mdf/mdf.py
A simple definition in the form of the others. Below is a sample proposed condition configuration in json mdf
```json
{
"node": {
"A": {
"type": "and",
"args": {
"dependency": [
{
"type": "timeinterval",
"args": {
"start": 0,
"end": 1000,
"interval": 2,
"unit": "ms"
}
},
{
"type": "threshold",
"args": {
"dependency": "A",
"parameter": "value",
"threshold": "10",
"direction": "<="
}
}
]
}
},
"B": {
"type": "whenfinished",
"args": {
"dependency": "A"
}
},
"C": {
"type": "everyncalls",
"args": {
"dependency": "B",
"calls": 2
}
}
},
"termination": {
"run": {
"type": "afterntrials",
"args": {
"trials": 5
}
},
"trial": {
"type": "afterncalls",
"args": {
"dependency": "C",
"calls": 1
}
}
}
}
```
=> mdf: add Condition definition

LICENSE
=> Change to Apache-2 license

examples/Quantum/README.md
Brief info about the envisioned work, which we expect to commence this summer.
=> Update Quantum README

examples/ACT-R/addition.json, examples/ACT-R/addition.yaml, examples/ACT-R/count.json, examples/ACT-R/count.yaml, examples/MDF/abc_conditions.json, examples/MDF/abc_conditions.py, examples/MDF/abc_conditions.yaml, examples/MDF/translation/Translated_abc_conditions.json, setup.cfg, src/modeci_mdf/interfaces/actr/exporter.py
Mainly for dependency -> dependencies rename
=> requirements: update for graph-scheduler v1.0.0rc2

src/modeci_mdf/execution_engine.py
Parse TimeScale string representations into TimeScale objects. Avoid hiding errors when parsing Conditions from JSON/YAML. Handle variable positional arguments specified as keyword arguments in JSON/YAML.
=> Improve condition parsing

src/modeci_mdf/interfaces/actr/exporter.py
Mentioned in #127, the exception caused by this condition is hidden. Is this the correct resolution @jeremyrl7?
=> ACT-R exporter: fix termination condition

src/modeci_mdf/execution_engine.py
depending on how a Graph is created (using classes in a script or parsed
from json/yaml), ConditionSet attributes node_specific and termination
may contain either dictionaries or Condition objects
=> execution_engine: fix condition parsing

README.md
I tried to work on the issue #208 and added a part on how to install this package. I felt this problem while installing, being a beginner.
=> Add installation part to readme

README.md
#219 
@pgleeson 
@sanjayankur31
=> added installation guide in readme.md

CONTRIBUTING.md, README.md
I got few errors in installing the dependencies without creating a virtual environment, so added it in the readme file so that the future contributors don't face the same issue.
=> Update in CONTRIBUTING.md

src/modeci_mdf/execution_engine.py, src/modeci_mdf/mdf.py, tests/conftest.py, tests/test_execution.py, tests/test_model.py, tests/test_scheduler.py
Solves issues related to nested conditions (needed for conditions like Any, All, Not, etc) when exporting or importing from serialized formats
=> Condition parsing

src/modeci_mdf/execution_engine.py, tests/test_scheduler.py
Threshold needs to access values of Evaluable objects during execution
=> Support Threshold condition

src/modeci_mdf/execution_engine.py, src/modeci_mdf/mdf.py, tests/test_helpers.py
expressions containing multiple items with subscripts or nested
subscripts previously failed during sympy.simplify
=> execution engine: condense and extend expression variable detection

docs/sphinx/requirements.txt
updated the requirement file from docs to optional to install the documentation related dependencies
=> fix for readthedocs

src/modeci_mdf/execution_engine.py
Consider this model
````
M:
format: ModECI MDF v0.4
generating_application: Python modeci-mdf v0.4.2
graphs:
G:
nodes:
n:
functions:
f:
args:
x: g
y: 1
value: x
g:
args:
x: f
value: x
````
Currently this will result in an infinite loop, solved by adcfa0ba42a2cd4cf2d463564d7b19d10fa9b496
It will then produce an error
````
Exception: Error! Could not evaluate function: f with args {'x': 'g', 'y': 1} using known vars ['constant']
````
I found that the changes in 0e4798df8105cd156be8d31732629e4895facfe3 were very helpful while I was debugging a model with a lot of variables, and they would instead produce the error
````
ValueError: Error! Could not evaluate functions using known vars. The following vars are missing:
f: g
g: f
````
=> execution_engine: improve error checking for missing vars

setup.cfg
@kusanele Merge in this PR and your tests should pass (but double check you have run pre-commit though)  
@Monsurat-Onabajo You will probably need to pull the latest from development too.
=> Fixes for tests

.gitignore, examples/NeuroML/LEMS_SimABCD.xml, examples/NeuroML/LEMS_SimFN.xml, examples/NeuroML/LEMS_SimIzhikevichTest.xml, tests/test_examples.py
@Monsurat-Onabajo Merge this and your tests should pass.
=> Fix for tests 

examples/PsyNeuLink/stroop_conflict_monitoring.py, setup.cfg
Fix stroop example to use input_shapes in place of size.
=> Remove upper pin on PNL, add lower pin.

examples/MDF/abcd_torch.py, setup.cfg, src/modeci_mdf/interfaces/pytorch/importer.py
Minor fixes for newer pytorch.
=> Remove pytorch upper pin
